# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvHV70yBXTGsusga49P1SYkgN_GzPNld
"""

import pandas as pd
baza={
    "Fish":[  'Ahmadjonov Diyorbek','Matkarimov Abbosbek','Aliyeva Zebo ','Qosimjonova Rayhona','Azimov Sarvar','Mamatvaliyev Dilshod','aliyev vali','rustamova sayyora','ravshanova mahliyo','Abduxalilova Robiya'  ],
    "Yoshi":[  '19','19','15','35','51','11','24','19','22','20'],
    "Jinsi":[  'erkak','erkak','ayol','ayol','erkak','erkak','erkak','ayol','ayol','ayol' ],
    "O'qish Joyi ":[    'TATUFF','TATUFF','3-maktabda' ,'54-maktab','kolej','36-maktab','78-maktab','FARDU','TOSHDU','UBS'    ],
    "Manzili":[    'Namangan','Xorazm','sirdaryo','fargona','andijon','samarqand' ,'Jizzax' ,'Andijon','Namangan','Namangan'      ]


}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Jinsi']=="ayol"]
print(filtr)

saralash=filtr[filtr['Manzili']=="Namangan"]
print(saralash)